# -*- coding: utf-8 -*-
"""HF_sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YemXeIxtuVNPZM0hLn5NCocjqa0DyNS2
"""

import pandas as pd

df = pd.read_excel('/content/merged_output(1).xlsx')
print("DataFrame loaded successfully. Displaying the first 5 rows:")
df.head()

!pip install transformers

!pip install torch

from transformers import pipeline
sentiment_pipeline = pipeline('sentiment-analysis')
print("Sentiment analysis pipeline loaded successfully.")

df['Abstract'] = df['Abstract'].fillna('').apply(lambda x: x[:512])
sentiment_results = sentiment_pipeline(df['Abstract'].tolist())
df['sentiment'] = [result['label'] for result in sentiment_results]
df['sentiment_score'] = [result['score'] for result in sentiment_results]
print("Sentiment analysis completed for the 'Abstract' column.")
print(df[['Abstract', 'sentiment', 'sentiment_score']].head())

import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries for visualization imported successfully.")

plt.figure(figsize=(8, 6))
sns.countplot(x='sentiment', data=df, palette='viridis')
plt.title('Distribution of Sentiment in Article Titles')
plt.xlabel('Sentiment')
plt.ylabel('Number of Articles')
plt.show()
print("Sentiment distribution visualization completed.")

plt.figure(figsize=(8, 6))
sns.countplot(x='sentiment', data=df, palette='viridis', hue='sentiment', legend=False)
plt.title('Distribution of Sentiment in Article Titles')
plt.xlabel('Sentiment')
plt.ylabel('Number of Articles')
plt.show()
print("Sentiment distribution visualization completed.")

sentiment_counts = df['sentiment'].value_counts()
print("\nSentiment Distribution:")
print(sentiment_counts)

most_common_sentiment = sentiment_counts.idxmax()
percentage_most_common = (sentiment_counts.max() / sentiment_counts.sum()) * 100

summary = f"\nSummary of Sentiment Analysis:\n"
summary += f"The majority of article titles ({percentage_most_common:.2f}%) were classified as '{most_common_sentiment}'."
if len(sentiment_counts) > 1:
    least_common_sentiment = sentiment_counts.idxmin()
    percentage_least_common = (sentiment_counts.min() / sentiment_counts.sum()) * 100
    summary += f" The remaining {percentage_least_common:.2f}% were classified as '{least_common_sentiment}'."
else:
    summary += f" All article titles were classified as '{most_common_sentiment}'."

print(summary)

from transformers import pipeline

sentiment_pipeline_model2 = pipeline('sentiment-analysis', model='cardiffnlp/twitter-roberta-base-sentiment-latest')
print("Second sentiment analysis pipeline loaded successfully with 'cardiffnlp/twitter-roberta-base-sentiment-latest'.")

import pandas as pd

df = pd.read_excel('/content/merged_output(1).xlsx')

df['Abstract'] = df['Abstract'].fillna('').apply(lambda x: x[:512])
sentiment_results_model2 = sentiment_pipeline_model2(df['Abstract'].tolist())
df['sentiment_model2'] = [result['label'] for result in sentiment_results_model2]
df['sentiment_score_model2'] = [result['score'] for result in sentiment_results_model2]
print("Sentiment analysis completed for the 'Abstract' column using the second model.")
print(df[['Abstract', 'sentiment_model2', 'sentiment_score_model2']].head())

from transformers import pipeline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

sentiment_pipeline = pipeline('sentiment-analysis')

df = pd.read_excel('/content/merged_output(1).xlsx')

df['Abstract'] = df['Abstract'].fillna('').apply(lambda x: x[:512])

sentiment_results = sentiment_pipeline(df['Abstract'].tolist())
df['sentiment'] = [result['label'] for result in sentiment_results]
df['sentiment_score'] = [result['score'] for result in sentiment_results]

sentiment_pipeline_model2 = pipeline('sentiment-analysis', model='cardiffnlp/twitter-roberta-base-sentiment-latest')

sentiment_results_model2 = sentiment_pipeline_model2(df['Abstract'].tolist())
df['sentiment_model2'] = [result['label'] for result in sentiment_results_model2]
df['sentiment_score_model2'] = [result['score'] for result in sentiment_results_model2]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

sns.countplot(x='sentiment', data=df, palette='viridis', ax=ax1, hue='sentiment', legend=False)
ax1.set_title('Sentiment Distribution (Model 1)')
ax1.set_xlabel('Sentiment (Model 1)')
ax1.set_ylabel('Number of Articles')

sns.countplot(x='sentiment_model2', data=df, palette='viridis', ax=ax2, hue='sentiment_model2', legend=False)
ax2.set_title('Sentiment Distribution (Model 2)')
ax2.set_xlabel('Sentiment (Model 2)')
ax2.set_ylabel('Number of Articles')

plt.tight_layout()
plt.show()
print("Sentiment distributions from both models visualized successfully.")

from transformers import pipeline

sentiment_pipeline_alt = pipeline('sentiment-analysis', model='finiteautomata/bertweet-base-sentiment-analysis', device=-1) # Force CPU usage
print("Alternative sentiment analysis pipeline (bertweet-base) loaded successfully and set to use CPU.")

sentiment_pipeline_bert_sst2 = pipeline('sentiment-analysis', model='textattack/bert-base-uncased-SST-2', device=-1)
print("bert-base-uncased-finetuned-sst2 sentiment analysis pipeline loaded successfully and set to use CPU.")

alt_results = sentiment_pipeline_alt(df['Abstract'].tolist(), truncation=True)
df['sentiment_alt'] = [result['label'] for result in alt_results]
df['sentiment_score_alt'] = [result['score'] for result in alt_results]

bert_sst2_results = sentiment_pipeline_bert_sst2(df['Abstract'].tolist(), truncation=True)
df['sentiment_bert_sst2'] = [result['label'] for result in bert_sst2_results]
df['sentiment_score_bert_sst2'] = [result['score'] for result in bert_sst2_results]

print("Sentiment analysis completed for the 'Abstract' column using the alternative model and bert-base-uncased-finetuned-sst2.")
print(df[['Abstract', 'sentiment_alt', 'sentiment_score_alt', 'sentiment_bert_sst2', 'sentiment_score_bert_sst2']].head())

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(18, 6))

sns.countplot(x='sentiment_alt', data=df, palette='viridis', hue='sentiment_alt', legend=False, ax=axes[0])
axes[0].set_title('Overall Sentiment Distribution (bertweet-base)')
axes[0].set_xlabel('Sentiment')
axes[0].set_ylabel('Number of Articles')

sns.countplot(x='sentiment_bert_sst2', data=df, palette='viridis', hue='sentiment_bert_sst2', legend=False, ax=axes[1])
axes[1].set_title('Overall Sentiment Distribution (bert-base-uncased-finetuned-sst2)')
axes[1].set_xlabel('Sentiment')
axes[1].set_ylabel('Number of Articles')

plt.tight_layout()
plt.show()
print("Overall sentiment distributions for both models displayed successfully.")

print("Sentiment Distribution for Original Model (distilbert-base-uncased-finetuned-sst-2-english):")
print(df['sentiment'].value_counts(normalize=True) * 100)

print("\nSentiment Distribution for Model 2 (cardiffnlp/twitter-roberta-base-sentiment-latest):")
print(df['sentiment_model2'].value_counts(normalize=True) * 100)

print("\nSentiment Distribution for Alternative Model (finiteautomata/bertweet-base-sentiment-analysis):")
print(df['sentiment_alt'].value_counts(normalize=True) * 100)

print("\nSentiment Distribution for BERT-base-uncased-finetuned-sst2 (textattack/bert-base-uncased-SST-2):")
print(df['sentiment_bert_sst2'].value_counts(normalize=True) * 100)